apiVersion: v1
kind: Service
metadata:
  name: aspnetapp-k8s
  labels:
    app: aspnetapp-k8s
spec:
  type: LoadBalancer
  selector:
    app: aspnetapp-k8s
  ports:
  - port: 4999
    name: http
    targetPort: 4999
    nodePort: 4999
  - port: 5000
    name: grpc
    targetPort: 5000
    nodePort: 5000